// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://objyddwihcupdeflwcty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ianlkZHdpaGN1cGRlZmx3Y3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjIyMTQsImV4cCI6MjA2MDEzODIxNH0.ZBgd87fJfL7lSWMxcsIx-F9PfkpLaRDSUCr5ZcG8zFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);